/*participer*/

DELIMITER |
	DROP PROCEDURE IF EXISTS ADD_PARTICIPATION;
	create procedure ADD_PARTICIPATION(NumCan int, Label varchar(25)) 
	BEGIN
		INSERT INTO PARTICIPATION(NumCandidat, LabelComp) VALUES (NumCan, Label);
	END;
|

DELIMITER |
	DROP PROCEDURE IF EXISTS DEL_PARTICIPATION;
	create procedure DEL_PARTICIPATION(NumCan int, Label varchar(25)) 
	BEGIN
		DELETE FROM PARTICIPER  wHERE NumCandidat=NumCan and LabelComp=Label;
	END;

|
DELIMITER |
	DROP PROCEDURE IF EXISTS GET_PARTICIPATION;
	create procedure GET_PARTICIPATION () 
	BEGIN
		SELECT NomCandidat, NomComp
		FROM PARTICIPER, CANDIDAT, COMPETITION
		WHERE CANDIDAT.NumCandidat=PARTICIPER.NumCandidat
		AND COMPETITION.LabelComp=PARTICIPER.LabelComp;
	END;	
|

DELIMITER |
	
	CREATE TRIGGER before_del_comp BEFORE DELETE
	ON COMPETITION FOR EACH ROW
	BEGIN
		
 		DELETE FROM PARTICIPER
 		WHERE LabelComp = Old.LabelComp;
	END;	
|
